app/config/urls.py
# from core.erp.views import myFirstView
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('primeraurl/', include('core.erp.urls'))
    path('erp/', include('core.erp.urls')),
    path('', IndexView.as_view(), name='homepage'),
    path('login/', LoginFormView.as_view(), name='login'),
    # path('logout/', LogoutView.as_view()),
    path('logout/', LogoutRedirectView.as_view(), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/erp/urls.py
from os import name
# from core.erp.views import myFirstView, mySecondView, prueba
from core.erp.views.category.views import CategoryCreateView, CategoryDeleteView, CategoryFormView, CategoryListView, CategoryUpdateView, category_list
from django.urls import path

from core.erp.views.dashboard.views import DashboardView
from core.erp.views.product.views import ProductCreateView, ProductDeleteView, ProductListView, ProductUpdateView
from core.erp.views.test.views import TestView, ReportePersonalizadoExcel
from core.erp.views.client.views import ClientView

# Especifcinado nombre de las rutas
app_name = 'erp'

# Tambien se puede usar el namespace en el archivo url principal
urlpatterns = [
    # path('uno/', myFirstView, name='vista1'),
    # path('dos/', mySecondView,  name='vista2'),
    # path('tres/', prueba,  name='vista3'),
    # path('category/list/', category_list, name='category_list')
    path('category/list/', CategoryListView.as_view(), name="category_list"),
    path('category/add/', CategoryCreateView.as_view(), name="category_add"),
    path('category/edit/<int:pk>/', CategoryUpdateView.as_view(), name="category_edit"),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name="category_delete"),
    path('category/form/', CategoryFormView.as_view(), name="category_form"),
    # product
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),

    # client
    path('client/', ClientView.as_view(), name='client'),

    #Home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    #Test:
    path('test/', TestView.as_view(), name='test'),    
    path('descarga-excel/', ReportePersonalizadoExcel.as_view(), name='excel'),    
]

app/core/erp/views/dashboard/views.py
from django.views.generic import TemplateView


class DashboardView(TemplateView):
    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Panel de administrador'
        return context

app/templates/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>Example 3.0</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{list_url}}">{{entity}}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>

    <!-- bloque JS -->
    {% block javascript %}
        
    {% endblock javascript %}
        
    </body>
{% endblock %}

app/templates/dashboard.html
{% extends 'layout.html' %}

app/templates/footer.html
  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

app/templates/form.html
{% extends 'layout.html' %}
{% block content %}

<form id="formCreation" action="" method="post" enctype="multipart/form-data">
  <div class="card card-default">
    <div class="card-header">
      <h3 class="card-title">
        {{title}}
        
        {% if action == 'add' %}
        <i class="fas fa-plus"></i>
        {% else %}
        <i class="fas fa-edit"></i>
        {% endif %}
          
        
      </h3>
    </div>
    <div class="card-body">
      {% csrf_token %} 
      <input type="hidden" name="action" value="{{action}}">        
      {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="">{{field.label}}:</label>
            {{field}}
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <button type="submit" class="btn btn-primary btnRegistro">
        <i class="fas fa-save"></i> Guardar registro
      </button>
    </div>
  </div>   
</form>

<script>
  // Esto es para el FormView
    // {% if form.errors %}
    // let errors = '';
    //     {% for field in form  %}
    //         {% for error in field.errors  %}
    //             errors += '{{error}}\n'
    //         {% endfor %}
    //     {% endfor %}
    //     {% for error in form.non_field_errors  %}
    //             errors += '{{error}}\n'
    //     {% endfor %}
    //     Swal.fire({
    //         title: "Error!",
    //         text: errors,
    //         icon: "error",
    //         confirmButtonText: "Ok",
    //     });
    // {% endif %}

    // Sin formView
    let formCreation = document.getElementById('formCreation');
    formCreation.addEventListener('submit', (e) => {
      e.preventDefault();
      console.log(e.target)
      myForm = new FormData(e.target)
      console.log(myForm)

      confirmMessage(window.location.pathname, "POST", myForm, 'Creado correctamnete', function(){
        location.href = '{{list_url}}'
      });

      // fetch(
      //   // '{% url "erp:category_add" %}',
      //   window.location.pathname,
      //    {
      //   method: "POST",
      //   body: myForm,
      // }).then(rpta => rpta.json()).then(result => 
      //   {        
      //   if(!result.hasOwnProperty('error')){

      //     Swal.fire({
      //     title: 'Creado correctamente!',
      //     icon: 'success',
      //     // html: 'I will close in <b></b> milliseconds.',
      //     timer: 2000,
      //     timerProgressBar: true,
      //     showConfirmButton: false,
      //     }).then((result) => {
      //     if (result.dismiss === Swal.DismissReason.timer) {
      //       location.href = '{{list_url}}'
      //       }
      //     })

      //   } else {
      //     console.log(result)
      //     showFormErrors(result.error);
      //   }
      // }
      // ).catch(error => console.error('Error:', error));
    })


</script>

{% endblock %}

app/templates/home.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Jorge Zevallos</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.1.0/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.1.0/css/adminlte.min.css' %}">

<!-- jQuery -->
<script src="{% static 'lib/adminlte-3.1.0/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'lib/adminlte-3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'lib/adminlte-3.1.0/js/adminlte.min.js' %}"></script>
<!-- Sweet Alert -->
<script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>

<!-- js functions -->
<script src="{% static 'js/functions.js' %}"></script>
{% block head %}

{% endblock %}
</head>
{% block body %}

{% endblock %}


</html>

app/templates/index.html
{% extends 'body.html' %}


{% block content %}
    
{% endblock  %}
    

app/templates/index_old.html
{% extends 'body.html' %}


{% block content %}
    
{% endblock  %}
    

app/templates/layout.html
{% extends 'vtc/body.html' %}

app/templates/list.html
{% extends 'layout.html' %} {% load static %} 
{% block head %}
  <link
    rel="stylesheet"
    href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"
  />
  <link
    rel="stylesheet"
    href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"
  />
  <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
  <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
  <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
  {% block headlist %}
  
  {% endblock headlist %}
{% endblock %} {% block content %}

<div class="card card-default">
  <div class="card-header">
    <h3 class="card-title">
      <i class="fas fa-search"></i>
      {{title}}
    </h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <table class="table" id="tableData">
      <thead>
        {% block columns %} {% endblock columns %}
      </thead>
      <tbody>
        {% block rows %} {% endblock rows %}
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    
    {% block butttons_list %}
    <a href="{{create_url}}" type="button" class="btn btn-primary btnRegistro">
      <i class="fas fa-plus"></i> Crear nuevo registro
    </a>
      
    {% endblock butttons_list %}

    <button>Descargar Excel</button>
      
  </div>
  <!-- /.card-body -->
</div>
<!-- /.card -->

{% endblock %} {% block javascript %}
<script type="application/javascript">
  $(document).ready(function () {
    $("#tableData").DataTable({
      responsive: true,
      autoWidth: false,
    });

    // POST Usando FetchAPI
    /**
    let btnRegistro = document.querySelector(".btnRegistro");
    btnRegistro.addEventListener("click", () => {
      fetch('{% url "erp:category_list" %}', {
        method: "POST",
        body: JSON.stringify({id: 1}),
        headers: {
          "Content-Type": "application/json",
        },
      }).then(rpta => rpta.json()).then(result => console.log(result));
    });
    */

    //POST Usando Jquery
    $('.btnRegistro').on('click', function(){
      $.ajax({
        url: '{% url "erp:category_list" %}',
        type: 'POST',
        data: {id: 1},
        dataType: 'json'
      }).done(function(data){
        //Si todo sale bien
        console.log(data)
      }).fail(function(jqXHR, textStatus, errorThrown){
        console.log(`${textStatus}:${errorThrown}`)
      }).always(function(){
        console.log('siempre')
      })
    })

    
  
  });
</script>
{% endblock javascript %}

app/templates/main.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'lib/bootstrap-5.1.1-dist/css/bootstrap.min.css' %}">
    <script src="{% static 'lib/bootstrap-5.1.1-dist/js/bootstrap.min.js' %}"></script>
    <title>Document</title>
  </head>
  <body>

    <div class="container">

    
    
    <h1>Mi primera vista</h1>

    {% block content %} 
        {% for category in categories %}
            <li>{{category.name}}</li>
        {% endfor %} 
        
        {% if categories %}
            <p>Hay datos</p>
        {% else %}
            <p>No hay datos :c</p>
        {% endif %} 
    {% endblock content %}

    <p>{{name}}</p>

  </div>
  </body>
</html>

app/templates/second.html
{% extends 'index.html' %}



{% block content %} 


<a href="{% url 'erp:vista1'%}">Ir a la vista 1</a>

<br>
{% for product in products %}
    <li>{{product.name}}</li>
{% endfor %} 

{% if products %}
    <p>Hay datos</p>
{% else %}
    <p>No hay datos :c</p>
{% endif %} 
{% endblock content %}

app/templates/tests.html
{% extends 'layout.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.css' %}"
/>
<script src="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
{% endblock head %} {% block content %}
<form id="formCreation" action="" method="post" enctype="multipart/form-data">
  <div class="card card-default">
    <div class="card-header">
      <h3 class="card-title">
        {{title}}
        <i class="fas fa-plus"></i>
      </h3>
    </div>
    <div class="card-body">
      <div class="form-group">
        <label for="">Categorias</label>
        {{form.categories}}
      </div>
      <div class="form-group">
        <label for="">Productos</label>
        {{form.productos}}
      </div>
      <div class="form-group">
        <label for="">Buscador</label>
        {{form.search}}
      </div>
    </div>
  </div>
</form>

<script>
  (function () {
    const categorySelect = document.getElementById("id_categories");
    const productoSelect = document.getElementById("id_productos");
    categorySelect.addEventListener("change", (e) => {
      const url = window.location.pathname;
      const idValue = e.target.value;
      if (idValue === "") {
        productoSelect.innerHTML = "";
        productoSelect.add(new Option(`---------`, ``));
      } else {
        console.log("idValueeee", idValue);
        const formData = new FormData();
        formData.append("action", "search_product_id");
        formData.append("id", idValue);

        fetch(url, {
          method: "POST",
          body: formData,
        })
          .then((rpta) => rpta.json())
          .then((result) => {
            // Vaciar lo que había antes y agregar el vacio
            productoSelect.innerHTML = "";
            productoSelect.add(new Option(`---------`, ``));
            result.forEach((producto) => {
              productoSelect.add(
                new Option(`${producto.name}`, `${producto.id}`)
              );
            });
          });
      }
    });

// Autocomplete jquery-ui
  $( "#id_search" ).autocomplete({
      source: async(request, response) => {
        data = new FormData()
        data.append('action', 'autocomplete')
        data.append('term', request.term)
        console.log(request.term)
        const rpta = await fetch(window.location.pathname, {
          method: 'POST',
          body: data
        });
        const values = await rpta.json()
        response(values)
      },
      delay: 500,
      minLength: 3,
      select: (event, ui) => {
        console.log(ui)
      }
    });

  })();

</script>

{% endblock %}